

one_big_film = "one_big_film1.mp4"

films = [
        {'name': "idle_2.mp4",
            'type': 'loop',
            'start': 0.0,
            'length': 0.0,
            'layer': 1,
        },
        {'name': "loop-under-construction.mp4",
            'type': 'loop',
            'start': 0.0,
            'length': 0.0,
            'disabled': True,
            'layer': 1,
        },
        {'name': "loop-cold-night.mp4",
            'type': 'loop',
            'start': 0.0,
            'length': 0.0,
            'disabled': True,
            'layer': 1,
        },
        {'name': "loop-swamp.mp4",
            'type': 'loop',
            'start': 0.0,
            'length': 0.0,
            'disabled': True,
            'layer': 1,
        },

        {'name': "tv-color-bars-distorted.mp4",
            'type': 'transition',
            'start': 0.0,
            'length': 1.0,
            'layer': 9,
        },
        {'name': "tv-color-bars.mp4",
            'type': 'transition',
            'start': 0.0,
            'length': 1.0,
            'disabled': True
            'layer': 9,
        },
        {'name': "tv-color-calibration.mp4",
            'type': 'transition',
            'start': 0.0,
            'length': 1.0,
            'layer': 9,
        },
        {'name': "tv-static-transition.mp4",
            'type': 'transition',
            'start': 0.0,
            'length': 1.0,
            'layer': 9,
        },

        {'name': "commercial_full.mp4",
            'type': 'content',
            'start': 0.0,
            'length': 45.0,
            'layer': 5,
        },
        {'name': "commercial_full.mp4",
            'type': 'content',
            'start': 45.0,
            'length': 45.0,
            'layer': 5,
        },
        {'name': "commercial_full.mp4",
            'type': 'content',
            'start': 90.0,
            'length': 45.0,
            'layer': 5,
        },
        {'name': "commercial_full.mp4",
            'type': 'content',
            'start': 135.0,
            'length': 45.0,
            'layer': 5,
        },
        {'name': "hairtwirl_with_static.mp4",
            'type': 'content',
            'start': 0.0,
            'length': 45.0,
            'layer': 5,
        },
        {'name': "1960s-baltimore-family.mp4",
            'type': 'content',
            'start': 0.0,
            'length': 5.0,
            'layer': 5,
        },
        {'name': "1960s-cuba-family.mp4",
            'type': 'content',
            'start': 0.0,
            'length': 5.0,
            'layer': 5,
        },
        {'name': "1960s-family-movie.mp4",
            'type': 'content',
            'start': 0.0,
            'length': 5.0,
            'layer': 5,
        },
        {'name': "1960s-family-vacation-keys.mp4",
            'type': 'content',
            'start': 0.0,
            'length': 5.0,
            'layer': 5,
        },
        {'name': "1960s-suburban-family.mp4",
            'type': 'content',
            'start': 0.0,
            'length': 5.0,
            'layer': 5,
        },
        {'name': "1960s-uncle-howie-house.mp4",
            'type': 'content',
            'start': 0.0,
            'length': 5.0,
            'layer': 5,
        },
    ]
