

films = [
        {'file': "loop-idle1.mp4",
            'type': 'loop',
         },
        {'file': "loop-under-construction.mp4",
            'type': 'loop',
            'disabled': True,
         },
        {'file': "loop-cold-night.mp4",
            'type': 'loop',
            'disabled': True,
         },
        {'file': "loop-swamp.mp4",
            'type': 'loop',
            'disabled': True,
         },

        {'file': "tv-color-bars-distorted.mp4",
            'type': 'transition',
            'length': 1.0,
         },
        {'file': "tv-color-bars.mp4",
            'type': 'transition',
            'length': 1.0,
            'disabled': True,
         },
        {'file': "tv-color-calibration.mp4",
            'type': 'transition',
            'length': 1.0,
         },
        {'file': "tv-static-transition.mp4",
            'type': 'transition',
            'length': 1.0,
         },

        {'file': "content-remote1.mp4",
            'type': 'content',
            'length': 45.0,
            'trigger': 'remote',
         },
        {'file': "content-remote1.mp4",
            'type': 'content',
            'start': 45.0,
            'length': 45.0,
            'trigger': 'remote',
         },
        {'file': "content-remote1.mp4",
            'type': 'content',
            'start': 90.0,
            'length': 45.0,
            'trigger': 'remote',
         },
        {'file': "content-remote1.mp4",
            'type': 'content',
            'start': 135.0,
            'length': 45.0,
            'trigger': 'remote',
         },
        {'file': "content-hair1.mp4",
            'type': 'content',
            'length': 45.0,
            'trigger': 'hair',
         },
        {'file': "content-phone1.mp4",
            'type': 'content',
            'length': 51.0,
            'trigger': 'phone',
         },
        {'file': "1960s-baltimore-family.mp4",
            'type': 'content',
            'length': 5.0,
         },
        {'file': "1960s-cuba-family.mp4",
            'type': 'content',
            'length': 20.0,
            'trigger': 'default',
         },
        {'file': "1960s-family-movie.mp4",
            'type': 'content',
            'length': 5.0,
         },
        {'file': "1960s-family-vacation-keys.mp4",
            'type': 'content',
            'length': 5.0,
         },
        {'file': "1960s-suburban-family.mp4",
            'type': 'content',
            'length': 5.0,
         },
        {'file': "1960s-uncle-howie-house.mp4",
            'type': 'content',
            'length': 5.0,
         },
    ]
